### ISSUE TITLE
Question about isSchemaSerializer

### ISSUE THREAD

**Issue by davidhernandeze** [endel/colyseus-pixijs-boilerplate#1]
Hi, good job making this example, I'm reading the code and I don't understand the variable 

`isSchemaSerializer`

Can you help me with a little explanation?

tnks!

**Comment by endel** [comment]
Hi @davidhernandeze, this is for demonstration purposes between the two available state serialization options: https://docs.colyseus.io/state/overview/

The Fossil Delta is going to be deprecated soon, though. I suggest only using the Schema serializer. 

Cheers!

**Comment by davidhernandeze** [comment]
Thanks!
