### ISSUE TITLE
       - Node version not specified in package.json

### ISSUE THREAD

**Issue by ghost** [endel/colyseus-pixijs-boilerplate#3]
Heroku says        - Node version not specified in package.json

**Comment by endel** [comment]
Hi @qertyuiop12345678, can you try adding this to your `package.json`:

```javascript
  // ...
  "engines": {
    "node": ">=14.16.0"
  },
  // ...
```

**Comment by endel** [comment]
I've updated this project's package.json, and it is now deployable on heroku!

**Comment by ghost** [comment]
Thanks alot!
